############################################################
# Log4j2 Configuration
############################################################

# Root logger configuration
status = warn
name = PropertiesConfig

############################################################
# Appenders
############################################################

# Console Appender
appender.console.type = Console
appender.console.name = Console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level %C{1}:%L - %msg%n

# File Appender
appender.file.type = File
appender.file.name = FileLogger
appender.file.fileName = ${sys:user.dir}/logs/abstract_machine.log
appender.file.createOnDemand = true
appender.file.append = true
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5level %C{1}:%L - %msg%n

############################################################
# Loggers
############################################################

# Console Logger
logger.AbstractMachine.name = AbstractMachine
logger.AbstractMachine.level = debug
logger.AbstractMachine.additivity = false
logger.AbstractMachine.appenderRef.console.ref = Console

# File Logger
logger.FileLogger.name = FileLogger
logger.FileLogger.level = all
logger.FileLogger.additivity = false
logger.FileLogger.appenderRef.file.ref = FileLogger

# Root logger
rootLogger.level = all
rootLogger.appenderRef.console.ref = Console
rootLogger.appenderRef.file.ref = FileLogger
